[project]
name = "commute_dm"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Adrien Rougny", email = "adrienrougny@gmail.com"},
]
dependencies = [
    "notebook>=7.1.2",
    "jupyterlab-freeze>=0.1.0",
    "neomodel>=5.4.3",
    "pybiomart>=0.2.0",
    "momapy @ git+http://github.com/adrienrougny/momapy.git@develop",
    "momapy_kb @ git+http://github.com/adrienrougny/momapy_kb.git",
    "neo4j_dm @ git+http://github.com/adrienrougny/neo4j_dm.git",
    "minervapy @ git+http://github.com/adrienrougny/minervapy.git",
    "pickleshare>=0.7.5",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm]
distribution = true

[build-system]
requires = ["pdm-backend"]
build-backend = "pdm.backend"
