[project]
name = "commute_dm"
version = "0.1.0"
description = "Default template for PDM package"
authors = [{ name = "Adrien Rougny", email = "adrienrougny@gmail.com" }]
dependencies = [
  "jupyterlab-freeze>=0.1.0",
  "jupyterlab>=4.5.6",
  "pydot",
  "boltons",
  # "rpy2",
  "pybiomart>=0.2.0",
  "momapy-kb[neo4j]",
  "momapy[skia]",
  "fieldz-kb",
  "pylpg",
]
requires-python = ">=3.10"
readme = "README.md"
license = { text = "MIT" }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
momapy-kb = { path = "../../../code/momapy_kb", editable = true }
momapy = { path = "../../../code/momapy", editable = true }
fieldz-kb = { path = "../../../code/fieldz_kb", editable = true }
pylpg = { path = "../../../code/pylpg", editable = true }

[dependency-groups]
dev = ["jupyter-ruff>=0.3.1"]
